version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - mongo-db
  mongo-db:
    container_name: mongo-db
    image: mongo
    ports:
      - 27017:27017
