# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.1.0'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
          image: ravivbenami/cicddemo
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: './frontend/Dockerfile'

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
          image: ravivbenami/cicddemo
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: './backend/Dockerfile'
      
    - run: npm test

    - uses: CDNievas/heroku-action@v1.0 
      with:
          heroku_email: "ravivofficial@gmail.com"
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: "ravivcicd"

