# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.1.0'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: DockerHub Build And Push
      uses: Abhishek-070/Dockerhub-Build-Push@v1.0
      with:
          registry_url: 'registry.hub.docker.com/library/cicddemo'
          repository_name: 'cicddemo'
          user_name: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_version: 'v1.0'
          docker_file: './frontend'
    - name: Get pre step result output image_pull_url
      run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"

        
    - run: npm test
